### ISSUE TITLE
Switch to setup.py

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#1]
@mbaumer The `desc_package_template` sets up packages to use the stack, and eups, etc, with an appropriate setup shell script. I think we want to ignore this (for now) and use `setup.py` instead, like we do in OM10. Can you make this happen, please?

**Comment by drphilmarshall** [comment]
Actually, this could be tricky - I'll take a look first, and try and get some help from DESC CI.

**Comment by rbiswas4** [comment]
This depends on what your dependencies are. If you really need LSST software which is only available from eups, then it is likely very tricky.

**Comment by drphilmarshall** [comment]
We don't (yet) - so far we just want to develop collaboratively, using
`python setup.py develop`...

**Comment by rbiswas4** [comment]
Then it might not be hard, though it would be good to figure out what you are worried about ... I may have not thought about that at all.
