### ISSUE TITLE
Lensed quasar image positions and magnifications

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#14]
Each OM10 lensed quasar image needs to be assigned its correct position and magnitude, and then visualized with its own alpha value. The positions are in the OM10 `XIMG` and `YIMG` columns, while the magnification is in the `MAG` columns. The observed magnitude of the `i`th image is given by
```
m[i] = m_s - 2.5 * np.log10(mu[i])
```
where `m_s` is the source (ie, unlensed) magnitude from `MAGI_IN` (or the painted equivalent), and `mu` is the magnification from the `MAG` array. If the magnification factor is 10, the image appears 2.5 magnitudes brighter than the source.

**Comment by drphilmarshall** [comment]
@jennykim1016 can you please reply to the email invitation to the slrealizer-developers team so that I can assign you issues on this repo? Thanks!

**Comment by jennykim1016** [comment]
I think I did not get an email -- the email invitation is not in my spam either. Would you mind sending me another email? Thanks!

**Comment by drphilmarshall** [comment]
OK, I edited the invitation and re-sent - you should see it in the email account you signed up to GitHub with. The previous invitation came from the DESC automated system, this time it might appear differently, as it's from me and to join the ["slrealizer-developers"](https://github.com/orgs/LSSTDESC/teams/slrealizer-developers) team. Keep me posted!

**Comment by jennykim1016** [comment]
Hmm, it is a little weird -- I did not get any email from Github regarding the invitation. Would there be any other way to accept the invitation? If I click the hyperlink embedded in `"slrealizer-developers"`, it shows 404 page not found error...

**Comment by drphilmarshall** [comment]
Can you check your spam folder please? I bet it's in there. GitHub didn't
get where it is today by being bad at sending automated emails ;-)

**Comment by jennykim1016** [comment]
It is not in spam folder either..... I am getting all the emails besides the invitation. I found out one email in my inbox that looks similar though(received 11/18/16); would accepting this invite be enough?

<img width="778" alt="screen shot 2017-04-01 at 10 29 34 am" src="https://cloud.githubusercontent.com/assets/18297066/24573951/504227a8-16c6-11e7-991e-5836027a0077.png">

**Comment by drphilmarshall** [comment]
Yes! That's the one. Sorry, I should have realized that the original would
have appeared to come from Tony.

**Comment by jennykim1016** [comment]
Oh, thanks! The link does not seem to work though. I think the link might have expired; I again see 404 Page Not Found error even though I have signed into this account...

**Comment by drphilmarshall** [comment]
@tony-johnson Can you please re-invite @jennykim1016 to the LSST DESC organization, with membership of the Members and SLRealizer-developers teams, please? The links in the original email invitation from your system have expired. Thanks! 

Jenny: please accept Tony's new invitation as soon as you get it!

**Comment by tony-johnson** [comment]
@jennykim1016 I updated your invitation, let me know if it does not work.

**Comment by jennykim1016** [comment]
@tony-johnson Thanks, but I haven't gotten any new invitation email from Github. I should be able to click [this link](https://github.com/orgs/LSSTDESC/teams/slrealizer-developers) to alternatively accept the invitation; however, I still see the 404 Page not found error if I click it...
I will contact Github Support and ask what the problem might be. I am so sorry for the inconvenience!

**Comment by jennykim1016** [comment]
@tony-johnson @drphilmarshall I just accepted the invitation directly through the organization site! Thanks.

**Comment by drphilmarshall** [comment]
Ah, good! I must remember about this alternative to responding to the
email. Glad you're in at last, jenny.
