### ISSUE TITLE
Python 2 vs Python 3?

### ISSUE THREAD

**Issue by jennykim1016** [LSSTDESC/SLRealizer#15]
I was reading PEP8 document, and I was not sure which version of python should we use. I remember for OM10 we used Python 2 with importing `__future__`'s print statement; should I do the same thing while coding? I have both versions of python, and changing from one to the other would not be a lot of changes if I do it now. Thanks!

**Comment by drphilmarshall** [comment]
It doesn't matter too much at this stage but in geeral we shoudl be
switching to python 3. I would support that change - it mainly means
importing from future and choosing python 3 in the notebook options. BTW
travis runs python 3 by default.

**Comment by drphilmarshall** [comment]
Closing this question now that we are issued with the upgrade to python 3 in #49
