### ISSUE TITLE
Toy mock Source table dataset

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#21]
Let's make ourselves a toy mock dataset to play with. 
It should have the following properties:

1. It should based on a realistic LSST selection of OM10 lensed quasars i.e. ~ 1000 lenses or whatever the standard LSST selection is
2. It should assume a null deblender, that leads to a single Source being cataloged at each visit epoch
3. The visit sequence will be that provided by Rahul in the "ObservingHistory" notebook
4. It should make reasonable assumptions about the observational errors
5. It should be stored as a csv format file that can be read in with Pandas
6. It should contain columns as follows: MJD, filter, ra, ra_err, dec, dec_err, flux, flux_err, qxx, qxx_err, qyy, qyy_err, qxy, qxy_err, psf_sigma, sky
7. The same assumed filter set and magnitude zero point as painted OM10

Some of these properties are placeholders for better LSST schema definitions, which we need to extract at some point ( see #3 )

**Comment by jennykim1016** [comment]
Hi Dr. Marshall,

Just to clarify, for RA and DEC, I suppose I should use the values from OM10 catalog. In this case, how would we use the first moment values that we calculated from the system with pseudo-images?  Even though we use a same lensed system, the first moment values seem to change from one observation to the other, but RA and DEC would be constant regardless.

Thanks in advance!

**Comment by drphilmarshall** [comment]
Good. In real life the RA and Dec in the LSST catalog will be outputs of
the source measuring software, which may well use first moments to define
source centroids. The OM10 catalog does _not_ contain RA and Dec values,
though - it gives QSO image positions relative to the lens galaxy position.
I believe there is example code in the OM10 repo to make output catalogs
with QSO image RAs and Decs, based on some input catalog of lens galaxy RA
and Dec. You shoudl look for this code, because it shows how to convert
small x and y offsets in arcsec into RA and Dec positions relative to the
lens galaxy Ra and Dec.

For the actual lens galaxy Ra and Dec values in our toy catalog, you can
take a small random number (within +/- 1 degree)  from the observation
history field center, which I believe should be

(RA, Dec) = (03:32:30, 10:00:24)

Watch out:
* A positive increase in Ra (ie a shift to the East) is a negative increase
in x (ie a shift to the left)
* An offset of x degrees to the East leads to an increase in RA of x *
cos(Dec) (because the lines of longitude converge at the poles, so the same
shift in RA means different angular separations at different declinations.

**Comment by drphilmarshall** [comment]
Looks like we are doing fine without RA and Dec being computed at all - and we have a Toy source catalog to play with. Closing out!
