### ISSUE TITLE
Refactor to subclass, streamline

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#29]
Hi @jiwoncpark ! 

When we met on Friday you said you were very close to finishing your re-factoring work: can you please submit a pull request to the master branch by Thursday 6pm? This will enable me to start the code review. I think you had also made progress on re-running the notebooks referred to in the DESC Note - great if you can submit those as well (with no outputs, as usual). We can close this issue when the PR is merged.

Thanks!

**Comment by drphilmarshall** [comment]
Revised deadline is Friday 12 noon PDT, following unavoidable class collision today. Hope it's going well, @jiwoncpark !

**Comment by jiwoncpark** [comment]
Closing because PR #32 was merged!
