### ISSUE TITLE
Investigate fast algebraic Gaussian moments

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#30]
@jiwoncpark I talked to @mbaumer , and he reported that he and Jenny did not hit problems with computing moments of the Gaussian mixtures directly - it was more that they had in mind comparing one model realization with another, and so needed a pseudo-image grid, and started down the GalSim road. Let's resurrect the idea of fast GMM moments for Source emulation! You have Roweis' [gaussian identities notes](https://cs.nyu.edu/~roweis/notes/gaussid.pdf), and here's one more tip from Mike: try using the [parallel axis theorem](https://en.wikipedia.org/wiki/Parallel_axis_theorem) to simplify taking moments of Gaussian components lying away from the field center. 

I think this should give a big speed-up (especially if you can vectorize the calculation of many Sources' moments). Have fun!

**Comment by jiwoncpark** [comment]
Implemented analytical moments!

**Comment by jiwoncpark** [comment]
Following file name conventions in PR #32 :

- For OM10Realizer, the relevant commit is 0e6e5b9020626a98fceec83802327875154326ef with the message "Add analytical moment calculation for OM10" and analytical formulas in `slrealizer/realize_om10.py`.
- For SDSSRealizer, the relevant commit is 1f1e9a173c2b68aa938f12f115126cd21586b60b with the message "Vectorize source table generation for SDSSRealizer" and analytical formulas in `slrealizer/realize_sdss.py`.

There are overlaps in the two so technically we can modularize the long function into smaller parts and place the overlapping parts in the parent class SLRealizer.

**Comment by drphilmarshall** [comment]
Excellent, thank you! +100 for vectorization
