### ISSUE TITLE
minion_1016 observation history

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#4]
We need a simple observation history input, to start realizing lenses as GMMs at different epochs. @rbiswas4, could you help us with this please? I think we just need a plain text (or csv) table containing OpSim visit ID (obshistID?), MJD, filter, image quality (PSF FWHM), and 5-sigma depth, for the WFD visits in the Twinkles field and `minion_1016`. I think you have this to hand, right? Thank you!

PS. @jbkalmbach You might like to follow this project, it's the one I was telling you about at the Hack Day. Medium term goals would be to incorporate your Twinkles error model in the catalog-level simulation, and to use the Twinkles lenses as a validation (?) set.

**Comment by rbiswas4** [comment]
@drphilmarshall And you wish to do this in the way we have been realizing Twinkles, ie. with no dithers and fieldID 1427 only. Is that correct?

**Comment by drphilmarshall** [comment]
For now, let's say yes: we just need something vaguely realistic to develop
against, and we have in mind validating against Twinkles so it makes sense
to use the same obs hist I think. Thanks!
