### ISSUE TITLE
Travis CI build failing at installing dependencies

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/SLRealizer#44]
Hopefully the [GalSim .travis.yml](https://github.com/GalSim-developers/GalSim/blob/releases/2.0/.travis.yml) file can help show us how to handle this! Here's the [error message on travis](https://travis-ci.org/LSSTDESC/SLRealizer/builds/418972867).

**Comment by jiwoncpark** [comment]
GalSim installation is now working but Travis build fails due to faulty LensPop installation at `issue/44/travis` 96e7db33c7e14e6bdb57d519110586a3c368e1e5

Fixing the LensPop packaging and module import structure at [my fork](https://github.com/jiwoncpark/LensPop)

**Comment by jiwoncpark** [comment]
Fixed with PR #48
